# Generated by Django 4.1.5 on 2023-01-16 11:47

from django.db import migrations, models
import hello_world_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_world_app", "0003_member_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="slugh_hash",
            field=models.CharField(
                default=hello_world_app.models.generate_slug_hash, max_length=8
            ),
        ),
    ]
