# Generated by Django 4.1.5 on 2023-01-16 15:17

from django.db import migrations, models
import hello_world_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_world_app", "0004_member_slugh_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="joined_date",
            field=models.DateField(
                default=hello_world_app.models.get_time_today, null=True
            ),
        ),
    ]
